<div class="space-y-6">

    {{-- Location --}}
    <div>
        {!! html()->label('Fulfillment Location', 'store_location_id')
            ->class('block mb-2 text-sm font-medium text-gray-700') !!}
        {!! html()->select('store_location_id', $locations->pluck('name', 'id'))
            ->class('block w-full px-3 py-2 border border-gray-300 rounded focus:outline-none focus:border-blue-500')
            ->required()
            ->placeholder('Select a location') !!}
        @error('store_location_id')
            <p class="text-red-600 mt-1 text-sm">{{ $message }}</p>
        @enderror
    </div>

    {{-- Idempotency key — generated by JS on page load to prevent duplicate submissions --}}
    <input type="hidden" name="idempotency_key" id="idempotency_key">

    {{-- Line Items --}}
    <div>
        <div class="flex justify-between items-center mb-3">
            <h3 class="text-sm font-semibold text-gray-700">Line Items</h3>
            <button type="button" id="add-item-btn"
                class="px-3 py-1.5 text-sm bg-gray-100 text-gray-700 rounded hover:bg-gray-200 transition">
                + Add Item
            </button>
        </div>

        @error('items')
            <p class="text-red-600 mb-3 text-sm">{{ $message }}</p>
        @enderror

        @if($errors->has('stock'))
            <div class="bg-red-50 border border-red-200 rounded p-3 mb-3 space-y-1">
                @foreach($errors->get('stock') as $stockMsgs)
                    @foreach((array) $stockMsgs as $msg)
                        <p class="text-red-700 text-sm">{{ $msg }}</p>
                    @endforeach
                @endforeach
            </div>
        @endif

        <div id="line-items-container" class="space-y-3">
            {{-- Initial row rendered by PHP; additional rows added by JS --}}
            <div class="line-item-row flex items-end gap-3 bg-gray-50 border border-gray-200 rounded p-3">
                <div class="flex-1 min-w-0">
                    <label class="block mb-1 text-xs font-medium text-gray-600">Product Variant</label>
                    <select name="items[0][product_variant_id]" required
                        class="block w-full px-3 py-2 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-500">
                        <option value="">Select variant</option>
                        @foreach($variantOptions as $id => $label)
                            <option value="{{ $id }}">{{ $label }}</option>
                        @endforeach
                    </select>
                    @error('items.0.product_variant_id')
                        <p class="text-red-600 mt-1 text-xs">{{ $message }}</p>
                    @enderror
                </div>
                <div class="w-32">
                    <label class="block mb-1 text-xs font-medium text-gray-600">Quantity</label>
                    <input type="number" name="items[0][quantity]" min="1" required
                        class="block w-full px-3 py-2 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-500"
                        placeholder="1">
                    @error('items.0.quantity')
                        <p class="text-red-600 mt-1 text-xs">{{ $message }}</p>
                    @enderror
                </div>
                <div class="flex-shrink-0 pb-0.5">
                    <button type="button" class="remove-item-btn px-2 py-2 text-red-400 hover:text-red-600 text-lg leading-none" style="display:none;" title="Remove">
                        &times;
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
(function () {
    // Generate a client-side idempotency key on page load
    const tsHex = Date.now().toString(16).toUpperCase();
    const randHex = Math.floor(Math.random() * 0xFFFFFF).toString(16).toUpperCase().padStart(6, '0');
    document.getElementById('idempotency_key').value = 'ik_' + tsHex + '_' + randHex;

    const variantOptions = @json($variantOptions);
    let rowIndex = 1;

    function buildOptions() {
        let html = '<option value="">Select variant</option>';
        for (const [id, label] of Object.entries(variantOptions)) {
            html += `<option value="${id}">${label}</option>`;
        }
        return html;
    }

    function refreshRemoveButtons() {
        const rows = document.querySelectorAll('.line-item-row');
        rows.forEach(row => {
            const btn = row.querySelector('.remove-item-btn');
            if (btn) btn.style.display = rows.length > 1 ? 'inline' : 'none';
        });
    }

    document.getElementById('add-item-btn').addEventListener('click', function () {
        const container = document.getElementById('line-items-container');
        const row = document.createElement('div');
        row.className = 'line-item-row flex items-end gap-3 bg-gray-50 border border-gray-200 rounded p-3';
        row.innerHTML = `
            <div class="flex-1 min-w-0">
                <label class="block mb-1 text-xs font-medium text-gray-600">Product Variant</label>
                <select name="items[${rowIndex}][product_variant_id]" required
                    class="block w-full px-3 py-2 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-500">
                    ${buildOptions()}
                </select>
            </div>
            <div class="w-32">
                <label class="block mb-1 text-xs font-medium text-gray-600">Quantity</label>
                <input type="number" name="items[${rowIndex}][quantity]" min="1" required
                    class="block w-full px-3 py-2 border border-gray-300 rounded text-sm focus:outline-none focus:border-blue-500"
                    placeholder="1">
            </div>
            <div class="flex-shrink-0 pb-0.5">
                <button type="button" class="remove-item-btn px-2 py-2 text-red-400 hover:text-red-600 text-lg leading-none" title="Remove">&times;</button>
            </div>
        `;
        container.appendChild(row);
        rowIndex++;
        refreshRemoveButtons();
    });

    document.getElementById('line-items-container').addEventListener('click', function (e) {
        if (e.target.closest('.remove-item-btn')) {
            e.target.closest('.line-item-row').remove();
            refreshRemoveButtons();
        }
    });
})();
</script>
